### ISSUE TITLE
Basic test suite for major functionality

### ISSUE THREAD

**Issue by brassy-endomorph** [scidsg/hushline#261]
# Summary

The app needs at a minimum a test suite to test the most major parts of the application.

## Tasks

- [x] Add `pytest` to the dev dependencies
- [x] Set up `conf.py` with necessary fixtures including `app` and `db` fixtures with a `function` scope
- [x] (Contingent) Refactor the application to ensure no global state and possibly use a `create_app` function and not a global `app` object
- [ ] Write tests !!!!

**Comment by brassy-endomorph** [comment]
Should not be implemented until #199 is implemented

**Comment by brassy-endomorph** [comment]
We have not written the tests. This should stay open.
