### ISSUE TITLE
Add linting/formatting

### ISSUE THREAD

**Issue by brassy-endomorph** [scidsg/hushline#263]
The code should have a linter applied to catch bugs and enforce consistent style across multiple contributors to reduce noise in diffs.

## Tasks

- [ ] Add and configure `isort`
- [ ] Add and configure `black`
- [ ] Add and configure `flake8`

## Misc.

Not using `ruff` which could replace the other tools as it feels clunk and immature and has some weird - ahem - _rough_ edges.

**Comment by brassy-endomorph** [comment]
Should not be implemented until #199 is implemented
