### ISSUE TITLE
Move CLI scripts into a cli.py module and integrate with Click

### ISSUE THREAD

**Issue by brassy-endomorph** [scidsg/hushline#266]
## Tasks

- [ ] Integrate `generate_invite_codes.py` with `click`
- [x] Remove `generate_codes.sh`
- [x] Integrate `init_db.py` with `click`
- [ ] Integrate `admin.py` with `click`
