### ISSUE TITLE
Setup automatic database migrations

### ISSUE THREAD

**Issue by brassy-endomorph** [scidsg/hushline#272]
We should use [`Flask-Migrate`](https://flask-migrate.readthedocs.io/en/latest/index.html) and [`alembic`](https://alembic.sqlalchemy.org/en/latest/) to handle database migrations. We can continue to use `db.create_all()` in testing.

We should setup metadata like so:

https://github.com/scidsg/frontpage/blob/73f85fb47f461829abf8d738a976613019fbc4dc/frontpage/db.py#L1-L14

# Tasks

- [x] Rename tables to be plural (e.g., a table containing `User` objects should be named `users`
- [ ] Ensure all tables have explicit table names
- [x] Set up metadata (see above)
- [ ] Set up initial migration to match current schema
- [ ] Set up script to auto-gen migrations on a fresh database
- [x] Configure `install.sh` to run `alembic` migrations via `flask db migrate` or whatever the builtin `Flask-Migrate` command is

**Comment by glenn-sorrentino** [comment]
Started working against this in the `migrations` branch

**Comment by brassy-endomorph** [comment]
This is not completed. Three of the tasks have not been addressed.

**Comment by glenn-sorrentino** [comment]
> This is not completed. Three of the tasks have not been addressed.

I addressed these in the PR for the installer
