### ISSUE TITLE
Cleanup DB migrations

### ISSUE THREAD

**Issue by brassy-endomorph** [scidsg/hushline#591]
Followup to #272 

- [ ] Ensure consistent naming conventions (also noted in #586)
- [ ] Ensure all tables have an explicit `__tablename__`
- [ ] Ensure all tables name are plural (for consistency)
- [ ] Remove empty revision `c2b6eff6e213_.py` (supersedes #547)
- [ ] Ensure (if possible) linear migrations (for now) to support easier auto-testing of migrations (relates to #555)
- [ ] Implement [Flask-Migrate](https://flask-migrate.readthedocs.io/en/latest/index.html) to give us a nice CLI for playing with migrations in dev
